### ISSUE TITLE
Reputation return "cannot read property 'activate' of undefined"

### ISSUE THREAD

**Issue by Geroto** [krues8dr/rpgmakermv-plugins#8]
Hello. I'm starting a new project in RPG Maker MV and try to use the Reputation Plugin. But when I click in Factions options in Menu the error message: "cannot read property 'activate' of undefined" appears in the scream.
![image](https://user-images.githubusercontent.com/80958564/142770431-94ec8ca2-286e-425c-8654-4d60ad0ddbdc.png)

Any tips of what is the cause of problem? I'm try to uninstal all the other plugins and still crash the game.
Thanks.

**Comment by krusynth** [comment]
@Geroto Thanks for the report. It looks like I had forgotten to update the plugin to use the latest version of Kru_Core - can you try the [new version I just uploaded](https://raw.githubusercontent.com/krusynth/rpgmakermv-plugins/release/Kru_Reputation.js) and see if it resolves the issue please? (Github is still updating their cache, so make sure it says version 1.0.1 when you download.) Thanks!

**Comment by Geroto** [comment]
@krusynth Hello and thanks for answer! I'm tried the new version of the plugin and it's work! Best regards!
